services:
  - type: web
    name: drm-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
